# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bsc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('company', models.CharField(max_length=32, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'bsc',
            },
        ),
        migrations.CreateModel(
            name='Bts',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=32, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('bsc_id', models.IntegerField()),
                ('altitude', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'bts',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bts_name', models.CharField(default='', max_length=32, null=True)),
                ('area_name', models.CharField(default='', max_length=16, null=True)),
                ('lac', models.IntegerField(default=0, null=True)),
                ('longitude', models.FloatField(default=0.0, max_length=8, null=True)),
                ('latitude', models.FloatField(default=0.0, max_length=8, null=True)),
                ('direction', models.IntegerField(default=0, null=True)),
                ('bcch', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'cell',
            },
        ),
        migrations.CreateModel(
            name='Ctrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Bsc')),
                ('bts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Bts')),
            ],
            options={
                'db_table': 'ctrl',
            },
        ),
        migrations.CreateModel(
            name='Distr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'distr',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pos', models.FileField(upload_to='./upload/')),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_file',
            },
        ),
        migrations.CreateModel(
            name='Fpnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('freq', models.IntegerField()),
            ],
            options={
                'db_table': 'fpnt',
            },
        ),
        migrations.CreateModel(
            name='idle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'idle',
            },
        ),
        migrations.CreateModel(
            name='Ms',
            fields=[
                ('imei', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('isdn', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=16)),
                ('company', models.CharField(max_length=32)),
                ('gsmmspsense', models.IntegerField()),
                ('gsmmsheight', models.FloatField()),
                ('gsmmspfout', models.FloatField()),
                ('mzone', models.FloatField()),
            ],
            options={
                'db_table': 'ms',
            },
        ),
        migrations.CreateModel(
            name='Msc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, null=True)),
                ('company', models.CharField(max_length=32, null=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('altitude', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'msc',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ntch', models.IntegerField()),
                ('traff', models.FloatField()),
                ('rate', models.FloatField()),
                ('thtraff', models.FloatField()),
                ('callnum', models.FloatField()),
                ('congsnum', models.FloatField()),
                ('callcongs', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('keynum', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('rxlev', models.FloatField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='Ant',
            fields=[
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='databasework.Cell')),
                ('antenna_high', models.IntegerField(null=True)),
                ('half_angle', models.IntegerField(null=True)),
                ('max_attenuation', models.IntegerField(null=True)),
                ('gain', models.IntegerField(null=True)),
                ('anttilt', models.IntegerField(null=True)),
                ('pt', models.IntegerField(null=True)),
                ('mspwr', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ant',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Cell'),
        ),
        migrations.AddField(
            model_name='phone',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Cell'),
        ),
        migrations.AddField(
            model_name='idle',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Cell'),
        ),
        migrations.AddField(
            model_name='idle',
            name='ms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Ms'),
        ),
        migrations.AlterUniqueTogether(
            name='fpnt',
            unique_together=set([('cell_id', 'freq')]),
        ),
        migrations.AddField(
            model_name='distr',
            name='cl_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl+', to='databasework.Cell'),
        ),
        migrations.AddField(
            model_name='distr',
            name='fn_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fn+', to='databasework.Cell'),
        ),
        migrations.AddField(
            model_name='cell',
            name='bts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Bts'),
        ),
        migrations.AddField(
            model_name='bsc',
            name='msc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databasework.Msc'),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('date', 'time', 'cell')]),
        ),
        migrations.AlterUniqueTogether(
            name='idle',
            unique_together=set([('cell', 'ms')]),
        ),
        migrations.AlterUniqueTogether(
            name='distr',
            unique_together=set([('cl_cell', 'fn_cell')]),
        ),
        migrations.AlterUniqueTogether(
            name='ctrl',
            unique_together=set([('bsc', 'bts')]),
        ),
    ]
