# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('CellID', models.IntegerField(primary_key=True, serialize=False)),
                ('BstName', models.CharField(default='', max_length=32, null=True)),
                ('AreaName', models.CharField(default='', max_length=16, null=True)),
                ('LAC', models.IntegerField(default=0, null=True)),
                ('Longitude', models.FloatField(default=0.0, max_length=8, null=True)),
                ('Latitude', models.FloatField(default=0.0, max_length=8, null=True)),
                ('Direction', models.IntegerField(default=0, null=True)),
                ('Bcch', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
