# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='bts_name',
        ),
        migrations.AddField(
            model_name='cell',
            name='radious',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='date',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
