# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databasework', '0002_auto_20160707_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='bts',
            field=models.ForeignKey(db_column='bts_name', on_delete=django.db.models.deletion.CASCADE, to='databasework.Bts'),
        ),
    ]
