# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasework', '0003_auto_20160707_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='distr',
            name='distance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
