# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databasework', '0004_distr_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsc',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bsc',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bsc',
            name='msc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databasework.Msc'),
        ),
        migrations.AlterField(
            model_name='bts',
            name='bsc_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bts',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bts',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='bts',
            field=models.ForeignKey(db_column='bts_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='databasework.Bts'),
        ),
        migrations.AlterField(
            model_name='msc',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='msc',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
