# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databasework', '0007_auto_20160708_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ant',
            name='cell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='databasework.Cell'),
        ),
    ]
